"""empty message

Revision ID: 457eec44aef7
Revises: a50cde241c4b
Create Date: 2023-10-04 14:40:45.041734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457eec44aef7'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
